<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqJ47no\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqJ47no/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRqJ47no.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRqJ47no\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRqJ47no\App_KernelDevDebugContainer([
    'container.build_hash' => 'RqJ47no',
    'container.build_id' => '90e4091d',
    'container.build_time' => 1669323781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqJ47no');
