<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVhi5ylB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVhi5ylB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVhi5ylB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVhi5ylB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVhi5ylB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vhi5ylB',
    'container.build_id' => 'f3947127',
    'container.build_time' => 1669373824,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVhi5ylB');
